-- Medical/Pharmaceutical Glossary seed data – EN → HU
-- British English (BMJ/Lancet standard), reviewed by Dr. Charlotte Hughes
-- Domains: Cardiology, Pharmacology, Immunology, Haematology, Hepatology,
--          Nephrology, Pulmonology, Neurology, Oncology, Endocrinology,
--          Gastroenterology, Anatomy, General Clinical

INSERT INTO termbase_entries
  (source_term, target_term, source_language, target_language, domain, definition, is_medical, notes)
VALUES

-- ── CARDIOLOGY ──────────────────────────────────────────────────────────
('myocardial infarction', 'szívinfarktus', 'en', 'hu', 'medical', 'Irreversible necrosis of heart muscle secondary to prolonged ischaemia.', true, NULL),
('angina pectoris', 'angina pectoris', 'en', 'hu', 'medical', 'Chest pain caused by reduced coronary blood flow, typically on exertion.', true, NULL),
('atrial fibrillation', 'pitvarfibrilláció', 'en', 'hu', 'medical', 'Irregular, often rapid heart rate caused by chaotic electrical activity in the atria.', true, 'Abbrev: AF'),
('heart failure', 'szívelégtelenség', 'en', 'hu', 'medical', 'Inability of the heart to pump sufficient blood to meet the body''s needs.', true, NULL),
('left ventricular ejection fraction', 'bal kamrai ejekciós frakció', 'en', 'hu', 'medical', 'Percentage of blood ejected from the left ventricle with each contraction.', true, 'Abbrev: LVEF'),
('coronary artery disease', 'koszorúér-betegség', 'en', 'hu', 'medical', 'Narrowing of the coronary arteries due to atherosclerosis.', true, 'Abbrev: CAD'),
('percutaneous coronary intervention', 'perkután koronária-intervenció', 'en', 'hu', 'medical', 'Minimally invasive procedure to open blocked coronary arteries.', true, 'Abbrev: PCI'),
('antiplatelet therapy', 'vérlemezkegátló kezelés', 'en', 'hu', 'pharmaceutical', 'Treatment that reduces platelet aggregation to prevent thrombus formation.', true, NULL),
('dual antiplatelet therapy', 'kettős vérlemezkegátló kezelés', 'en', 'hu', 'pharmaceutical', 'Combination of two antiplatelet agents, typically aspirin and a P2Y12 inhibitor.', true, 'Abbrev: DAPT'),
('P2Y12 inhibitor', 'P2Y12-gátló', 'en', 'hu', 'pharmaceutical', 'Drug class that blocks the platelet ADP receptor to inhibit aggregation.', true, NULL),
('cardiac tamponade', 'szívtamponád', 'en', 'hu', 'medical', 'Compression of the heart by fluid accumulation in the pericardial sac.', true, NULL),
('aortic stenosis', 'aortaszűkület', 'en', 'hu', 'medical', 'Narrowing of the aortic valve opening, obstructing left ventricular outflow.', true, NULL),
('ventricular tachycardia', 'kamrai tachycardia', 'en', 'hu', 'medical', 'Rapid heart rate originating from the ventricles.', true, 'Abbrev: VT'),
('bradycardia', 'bradycardia', 'en', 'hu', 'medical', 'Heart rate below 60 beats per minute.', true, NULL),
('hypertension', 'magas vérnyomás', 'en', 'hu', 'medical', 'Persistently elevated arterial blood pressure.', true, NULL),
('dyslipidaemia', 'diszlipidémia', 'en', 'hu', 'medical', 'Abnormal levels of lipids or lipoproteins in the blood.', true, NULL),
('pericarditis', 'pericarditis', 'en', 'hu', 'medical', 'Inflammation of the pericardium, the sac surrounding the heart.', true, NULL),
('thrombus', 'thrombus', 'en', 'hu', 'medical', 'Blood clot formed within a blood vessel.', true, NULL),
('embolism', 'embólia', 'en', 'hu', 'medical', 'Obstruction of a blood vessel by a detached clot, air bubble, or other material.', true, NULL),
('atherosclerosis', 'atherosclerosis', 'en', 'hu', 'medical', 'Buildup of plaques within arterial walls, reducing luminal diameter.', true, NULL),

-- ── PHARMACOLOGY ────────────────────────────────────────────────────────
('contraindication', 'ellenjavallat', 'en', 'hu', 'pharmaceutical', 'A condition that makes a particular treatment inadvisable.', true, NULL),
('adverse drug reaction', 'gyógyszer-mellékhatás', 'en', 'hu', 'pharmaceutical', 'Unintended, harmful response to a medication at a standard dose.', true, 'Abbrev: ADR'),
('pharmacokinetics', 'farmakokinetika', 'en', 'hu', 'pharmaceutical', 'Study of drug absorption, distribution, metabolism, and excretion.', false, NULL),
('pharmacodynamics', 'farmakodinamika', 'en', 'hu', 'pharmaceutical', 'Study of the biochemical and physiological effects of drugs on the body.', false, NULL),
('bioavailability', 'biohasznosíthatóság', 'en', 'hu', 'pharmaceutical', 'Proportion of a drug that reaches systemic circulation in unchanged form.', false, NULL),
('half-life', 'felezési idő', 'en', 'hu', 'pharmaceutical', 'Time required for the concentration of a drug to halve.', false, NULL),
('loading dose', 'telítő dózis', 'en', 'hu', 'pharmaceutical', 'Initial, larger dose given to rapidly achieve therapeutic drug levels.', false, NULL),
('maintenance dose', 'fenntartó dózis', 'en', 'hu', 'pharmaceutical', 'Regular dose given to sustain a therapeutic drug concentration.', false, NULL),
('drug interaction', 'gyógyszerkölcsönhatás', 'en', 'hu', 'pharmaceutical', 'Modified effect of a drug caused by concurrent use of another substance.', false, NULL),
('therapeutic index', 'terápiás index', 'en', 'hu', 'pharmaceutical', 'Ratio between the toxic dose and the therapeutic dose of a drug.', false, NULL),
('off-label use', 'engedélyen kívüli alkalmazás', 'en', 'hu', 'pharmaceutical', 'Use of a medicine in a manner not specified in its approved labelling.', false, NULL),
('excipient', 'segédanyag', 'en', 'hu', 'pharmaceutical', 'Inactive substance used as a carrier for active pharmaceutical ingredients.', false, NULL),
('active substance', 'hatóanyag', 'en', 'hu', 'pharmaceutical', 'Component of a drug product responsible for its therapeutic effect.', false, NULL),
('placebo', 'placebo', 'en', 'hu', 'pharmaceutical', 'Inert substance used as a control in clinical trials.', false, NULL),
('dose-dependent', 'dózisfüggő', 'en', 'hu', 'pharmaceutical', 'Effect that varies in proportion to the amount of drug administered.', false, NULL),
('monoamine oxidase inhibitor', 'monoamin-oxidáz-gátló', 'en', 'hu', 'pharmaceutical', 'Drug class that inhibits monoamine oxidase enzymes, used in depression and Parkinson''s disease.', true, 'Abbrev: MAOI'),
('beta-lactam antibiotic', 'béta-laktám antibiotikum', 'en', 'hu', 'pharmaceutical', 'Antibiotic class sharing a beta-lactam ring structure, including penicillins and cephalosporins.', true, NULL),
('anticoagulant', 'antikoaguláns', 'en', 'hu', 'pharmaceutical', 'Drug that inhibits blood coagulation.', true, NULL),
('fibrinolytic', 'fibrinolitikum', 'en', 'hu', 'pharmaceutical', 'Agent that dissolves fibrin clots; also called thrombolytic.', true, NULL),
('statin', 'sztatin', 'en', 'hu', 'pharmaceutical', 'HMG-CoA reductase inhibitor used to lower LDL cholesterol.', true, NULL),
('ACE inhibitor', 'ACE-gátló', 'en', 'hu', 'pharmaceutical', 'Angiotensin-converting enzyme inhibitor used in hypertension and heart failure.', true, NULL),
('beta-blocker', 'béta-blokkoló', 'en', 'hu', 'pharmaceutical', 'Drug that blocks beta-adrenergic receptors, reducing heart rate and blood pressure.', true, NULL),
('diuretic', 'diuretikum', 'en', 'hu', 'pharmaceutical', 'Drug that promotes the excretion of urine, reducing fluid volume.', true, NULL),
('proton pump inhibitor', 'protonpumpa-gátló', 'en', 'hu', 'pharmaceutical', 'Drug class that reduces gastric acid production by inhibiting H+/K+-ATPase.', true, 'Abbrev: PPI'),
('corticosteroid', 'kortikoszteroid', 'en', 'hu', 'pharmaceutical', 'Steroid hormone or synthetic analogue with anti-inflammatory and immunosuppressive effects.', true, NULL),
('non-steroidal anti-inflammatory drug', 'nem szteroid gyulladáscsökkentő', 'en', 'hu', 'pharmaceutical', 'Drug class that inhibits cyclooxygenase enzymes, reducing pain and inflammation.', true, 'Abbrev: NSAID'),
('immunosuppressant', 'immunszuppresszív szer', 'en', 'hu', 'pharmaceutical', 'Drug that reduces the activity of the immune system.', true, NULL),

-- ── IMMUNOLOGY / ALLERGY ─────────────────────────────────────────────────
('hypersensitivity', 'túlérzékenység', 'en', 'hu', 'medical', 'Exaggerated immune response to an antigen, potentially causing tissue damage.', true, NULL),
('anaphylaxis', 'anafilaxia', 'en', 'hu', 'medical', 'Severe, life-threatening systemic hypersensitivity reaction.', true, NULL),
('autoimmune disease', 'autoimmun betegség', 'en', 'hu', 'medical', 'Condition in which the immune system attacks the body''s own tissues.', true, NULL),
('antigen', 'antigén', 'en', 'hu', 'medical', 'Substance recognised by the immune system as foreign, triggering an immune response.', false, NULL),
('antibody', 'antitest', 'en', 'hu', 'medical', 'Immunoglobulin produced by B cells that binds specifically to an antigen.', false, NULL),
('immunoglobulin', 'immunglobulin', 'en', 'hu', 'medical', 'Glycoprotein functioning as an antibody, produced by plasma cells.', false, NULL),
('cytokine', 'citokin', 'en', 'hu', 'medical', 'Signalling protein secreted by immune cells that regulates immune responses.', false, NULL),
('inflammation', 'gyulladás', 'en', 'hu', 'medical', 'Biological response to harmful stimuli, characterised by redness, swelling, heat, and pain.', true, NULL),
('allergy', 'allergia', 'en', 'hu', 'medical', 'Immune system reaction to a normally harmless substance.', true, NULL),

-- ── HAEMATOLOGY ──────────────────────────────────────────────────────────
('anaemia', 'anaemia', 'en', 'hu', 'medical', 'Reduction in the number of red blood cells or haemoglobin concentration.', true, NULL),
('haemoglobin', 'hemoglobin', 'en', 'hu', 'medical', 'Iron-containing protein in red blood cells that carries oxygen.', false, NULL),
('platelet', 'vérlemezke', 'en', 'hu', 'medical', 'Small blood cell fragment involved in clotting.', false, NULL),
('platelet aggregation', 'vérlemezke-aggregáció', 'en', 'hu', 'medical', 'Clustering of platelets at sites of vascular injury, initiating coagulation.', true, NULL),
('coagulation', 'véralvadás', 'en', 'hu', 'medical', 'Process by which blood changes from a liquid to a gel, forming a clot.', true, NULL),
('international normalised ratio', 'INR', 'en', 'hu', 'medical', 'Standardised measure of blood coagulation time used to monitor anticoagulant therapy.', false, 'Abbrev: INR'),
('deep vein thrombosis', 'mélyvénás trombózis', 'en', 'hu', 'medical', 'Formation of a blood clot in a deep vein, usually in the leg.', true, 'Abbrev: DVT'),
('pulmonary embolism', 'tüdőembólia', 'en', 'hu', 'medical', 'Blockage of a pulmonary artery by a detached clot, usually from a DVT.', true, 'Abbrev: PE'),
('white blood cell', 'fehérvérsejt', 'en', 'hu', 'medical', 'Blood cell that forms part of the immune system.', false, 'Abbrev: WBC; also: leucocyte'),
('neutropenia', 'neutropenia', 'en', 'hu', 'medical', 'Abnormally low neutrophil count, increasing susceptibility to infection.', true, NULL),
('thrombocytopenia', 'thrombocytopenia', 'en', 'hu', 'medical', 'Abnormally low platelet count.', true, NULL),

-- ── HEPATOLOGY ───────────────────────────────────────────────────────────
('hepatic impairment', 'májelégtelenség', 'en', 'hu', 'medical', 'Reduced capacity of the liver to perform its normal functions.', true, NULL),
('cirrhosis', 'cirrhosis', 'en', 'hu', 'medical', 'Irreversible scarring of the liver, impairing its function.', true, NULL),
('hepatitis', 'hepatitis', 'en', 'hu', 'medical', 'Inflammation of the liver, most commonly caused by viral infection.', true, NULL),
('jaundice', 'sárgaság', 'en', 'hu', 'medical', 'Yellowing of the skin and sclerae caused by elevated bilirubin.', true, NULL),
('bilirubin', 'bilirubin', 'en', 'hu', 'medical', 'Breakdown product of haem metabolism excreted by the liver.', false, NULL),
('alanine aminotransferase', 'alanin-aminotranszferáz', 'en', 'hu', 'medical', 'Liver enzyme elevated in hepatocellular damage.', false, 'Abbrev: ALT'),
('aspartate aminotransferase', 'aszpartát-aminotranszferáz', 'en', 'hu', 'medical', 'Enzyme elevated in liver, cardiac, and muscle damage.', false, 'Abbrev: AST'),

-- ── NEPHROLOGY ───────────────────────────────────────────────────────────
('renal function', 'vesefunkció', 'en', 'hu', 'medical', 'Ability of the kidneys to filter blood and excrete waste products.', true, NULL),
('creatinine', 'kreatinin', 'en', 'hu', 'medical', 'Waste product of muscle metabolism, used as a marker of renal function.', false, NULL),
('glomerular filtration rate', 'glomeruláris filtrációs ráta', 'en', 'hu', 'medical', 'Rate at which the kidneys filter blood; key indicator of renal function.', false, 'Abbrev: GFR'),
('acute kidney injury', 'akut vesekárosodás', 'en', 'hu', 'medical', 'Sudden episode of kidney failure or damage within a short period.', true, 'Abbrev: AKI'),
('chronic kidney disease', 'krónikus vesebetegség', 'en', 'hu', 'medical', 'Long-standing, progressive loss of kidney function.', true, 'Abbrev: CKD'),
('proteinuria', 'proteinuria', 'en', 'hu', 'medical', 'Abnormal presence of protein in the urine, indicating kidney damage.', true, NULL),
('dialysis', 'dialízis', 'en', 'hu', 'medical', 'Procedure that removes waste and excess fluid from the blood when the kidneys cannot.', true, NULL),

-- ── PULMONOLOGY / RESPIRATORY ────────────────────────────────────────────
('asthma', 'asztma', 'en', 'hu', 'medical', 'Chronic inflammatory disease of the airways causing recurrent wheeze and breathlessness.', true, NULL),
('chronic obstructive pulmonary disease', 'krónikus obstruktív tüdőbetegség', 'en', 'hu', 'medical', 'Progressive lung disease characterised by airflow limitation.', true, 'Abbrev: COPD'),
('pneumonia', 'tüdőgyulladás', 'en', 'hu', 'medical', 'Infection causing inflammation of the alveoli, usually bacterial or viral.', true, NULL),
('dyspnoea', 'dyspnoea', 'en', 'hu', 'medical', 'Subjective sensation of difficulty or discomfort in breathing.', true, NULL),
('bronchospasm', 'bronchospasmus', 'en', 'hu', 'medical', 'Sudden constriction of the muscles in the walls of the bronchi.', true, NULL),
('spirometry', 'spirometria', 'en', 'hu', 'medical', 'Pulmonary function test measuring airflow and lung volumes.', false, NULL),
('oxygen saturation', 'oxigénszaturáció', 'en', 'hu', 'medical', 'Percentage of haemoglobin binding sites occupied by oxygen.', false, 'Abbrev: SpO2 (pulse oximetry), SaO2 (arterial)'),
('respiratory failure', 'légzési elégtelenség', 'en', 'hu', 'medical', 'Inability of the respiratory system to maintain adequate gas exchange.', true, NULL),

-- ── NEUROLOGY ────────────────────────────────────────────────────────────
('stroke', 'stroke', 'en', 'hu', 'medical', 'Sudden neurological deficit caused by interruption of blood supply to the brain.', true, NULL),
('transient ischaemic attack', 'tranziens ischaemiás attak', 'en', 'hu', 'medical', 'Brief episode of neurological dysfunction due to temporary cerebral ischaemia, resolving within 24 hours.', true, 'Abbrev: TIA'),
('epilepsy', 'epilepszia', 'en', 'hu', 'medical', 'Chronic neurological disorder characterised by recurrent unprovoked seizures.', true, NULL),
('seizure', 'roham', 'en', 'hu', 'medical', 'Sudden, uncontrolled electrical disturbance in the brain.', true, NULL),
('neuropathy', 'neuropátia', 'en', 'hu', 'medical', 'Damage or dysfunction of peripheral nerves.', true, NULL),
('dementia', 'demencia', 'en', 'hu', 'medical', 'Progressive decline in cognitive function affecting daily living.', true, NULL),
('migraine', 'migréne', 'en', 'hu', 'medical', 'Recurrent headache disorder, often unilateral and associated with nausea.', true, NULL),
('Parkinson''s disease', 'Parkinson-kór', 'en', 'hu', 'medical', 'Progressive neurodegenerative disorder characterised by tremor, rigidity, and bradykinesia.', true, NULL),

-- ── ONCOLOGY ─────────────────────────────────────────────────────────────
('malignancy', 'malignus daganat', 'en', 'hu', 'medical', 'Cancerous tumour with potential for invasion and metastasis.', true, NULL),
('metastasis', 'metasztázis', 'en', 'hu', 'medical', 'Spread of cancer cells from the primary site to distant organs.', true, NULL),
('chemotherapy', 'kemoterápia', 'en', 'hu', 'pharmaceutical', 'Treatment of cancer using cytotoxic drugs.', true, NULL),
('radiotherapy', 'sugárterápia', 'en', 'hu', 'medical', 'Treatment using ionising radiation to destroy cancer cells.', true, NULL),
('immunotherapy', 'immunoterápia', 'en', 'hu', 'pharmaceutical', 'Treatment that uses the immune system to fight cancer.', true, NULL),
('targeted therapy', 'célzott terápia', 'en', 'hu', 'pharmaceutical', 'Drug treatment that targets specific molecules involved in cancer growth.', true, NULL),
('tumour marker', 'tumormarker', 'en', 'hu', 'medical', 'Biomarker found in blood or tissue whose level indicates presence of cancer.', false, NULL),
('biopsy', 'biopszia', 'en', 'hu', 'medical', 'Removal and examination of tissue to diagnose disease.', false, NULL),

-- ── ENDOCRINOLOGY ────────────────────────────────────────────────────────
('diabetes mellitus', 'diabetes mellitus', 'en', 'hu', 'medical', 'Metabolic disease characterised by chronic hyperglycaemia due to insulin deficiency or resistance.', true, NULL),
('insulin resistance', 'inzulinrezisztencia', 'en', 'hu', 'medical', 'Reduced sensitivity of cells to the action of insulin.', true, NULL),
('hyperglycaemia', 'hiperglikémia', 'en', 'hu', 'medical', 'Abnormally elevated blood glucose concentration.', true, NULL),
('hypoglycaemia', 'hipoglikémia', 'en', 'hu', 'medical', 'Abnormally low blood glucose concentration.', true, NULL),
('hypothyroidism', 'hypothyreosis', 'en', 'hu', 'medical', 'Underactivity of the thyroid gland, leading to reduced hormone production.', true, NULL),
('hyperthyroidism', 'hyperthyreosis', 'en', 'hu', 'medical', 'Overactivity of the thyroid gland, leading to excess hormone production.', true, NULL),
('HbA1c', 'HbA1c', 'en', 'hu', 'medical', 'Glycated haemoglobin; reflects average blood glucose over the preceding 8-12 weeks.', false, NULL),
('insulin', 'inzulin', 'en', 'hu', 'pharmaceutical', 'Pancreatic hormone that regulates glucose uptake.', true, NULL),
('glucocorticoid', 'glükokortikoid', 'en', 'hu', 'pharmaceutical', 'Class of corticosteroids involved in glucose metabolism and immune suppression.', true, NULL),

-- ── GASTROENTEROLOGY ────────────────────────────────────────────────────
('gastro-oesophageal reflux disease', 'gastrooesophageális reflux betegség', 'en', 'hu', 'medical', 'Condition in which stomach acid flows back into the oesophagus.', true, 'Abbrev: GORD (British); GERD (American)'),
('peptic ulcer', 'peptikus fekély', 'en', 'hu', 'medical', 'Open sore on the lining of the stomach or duodenum.', true, NULL),
('inflammatory bowel disease', 'gyulladásos bélbetegség', 'en', 'hu', 'medical', 'Chronic inflammation of the digestive tract; includes Crohn''s disease and ulcerative colitis.', true, 'Abbrev: IBD'),
('irritable bowel syndrome', 'irritábilis bél szindróma', 'en', 'hu', 'medical', 'Functional disorder of the intestines causing abdominal pain and altered bowel habits.', true, 'Abbrev: IBS'),
('nausea', 'hányinger', 'en', 'hu', 'medical', 'Sensation of discomfort in the stomach with an urge to vomit.', false, NULL),
('gastrointestinal bleeding', 'gastrointestinalis vérzés', 'en', 'hu', 'medical', 'Blood loss from any part of the gastrointestinal tract.', true, NULL),

-- ── ANATOMY ──────────────────────────────────────────────────────────────
('heart muscle', 'szívizom', 'en', 'hu', 'medical', 'Specialised cardiac muscle tissue forming the bulk of the heart wall.', false, NULL),
('left ventricle', 'bal kamra', 'en', 'hu', 'medical', 'Lower left chamber of the heart that pumps oxygenated blood to the body.', false, NULL),
('right ventricle', 'jobb kamra', 'en', 'hu', 'medical', 'Lower right chamber of the heart that pumps deoxygenated blood to the lungs.', false, NULL),
('aorta', 'aorta', 'en', 'hu', 'medical', 'Main artery leaving the left ventricle, supplying oxygenated blood to the body.', false, NULL),
('coronary artery', 'koszorúér', 'en', 'hu', 'medical', 'Artery supplying blood to the heart muscle.', false, NULL),
('pulmonary artery', 'tüdőartéria', 'en', 'hu', 'medical', 'Artery carrying deoxygenated blood from the right ventricle to the lungs.', false, NULL),
('oesophagus', 'nyelőcső', 'en', 'hu', 'medical', 'Muscular tube connecting the pharynx to the stomach.', false, NULL),
('diaphragm', 'rekeszizom', 'en', 'hu', 'medical', 'Dome-shaped muscle separating the thoracic and abdominal cavities, essential for breathing.', false, NULL),

-- ── GENERAL CLINICAL ────────────────────────────────────────────────────
('diagnosis', 'diagnózis', 'en', 'hu', 'medical', 'Identification of a disease or condition by its signs and symptoms.', false, NULL),
('prognosis', 'prognózis', 'en', 'hu', 'medical', 'Predicted outcome of a disease.', false, NULL),
('sign', 'tünet (objektív)', 'en', 'hu', 'medical', 'Objective indicator of disease detectable by a clinician.', false, 'Distinguished from symptom, which is subjective'),
('symptom', 'panasz', 'en', 'hu', 'medical', 'Subjective experience reported by the patient.', false, NULL),
('acute', 'akut', 'en', 'hu', 'medical', 'Of rapid onset and short duration.', false, NULL),
('chronic', 'krónikus', 'en', 'hu', 'medical', 'Of long duration or slow progression.', false, NULL),
('comorbidity', 'komorbiditás', 'en', 'hu', 'medical', 'Presence of one or more additional conditions co-occurring with a primary condition.', false, NULL),
('mortality', 'mortalitás', 'en', 'hu', 'medical', 'Number of deaths in a given population over a defined period.', false, NULL),
('morbidity', 'morbiditás', 'en', 'hu', 'medical', 'State of being diseased; incidence or prevalence of disease.', false, NULL),
('aetiology', 'etiológia', 'en', 'hu', 'medical', 'Study of the causes or origins of a disease.', false, NULL),
('pathophysiology', 'patofiziológia', 'en', 'hu', 'medical', 'Study of the functional changes associated with disease.', false, NULL),
('idiopathic', 'idiopátiás', 'en', 'hu', 'medical', 'Of unknown cause.', false, NULL),
('palliative care', 'palliatív ellátás', 'en', 'hu', 'medical', 'Care focused on relieving symptoms and improving quality of life in serious illness.', false, NULL),
('informed consent', 'tájékozott beleegyezés', 'en', 'hu', 'medical', 'Patient agreement to treatment after receiving and understanding relevant information.', false, NULL),
('clinical trial', 'klinikai vizsgálat', 'en', 'hu', 'medical', 'Research study to evaluate the safety and efficacy of medical interventions in humans.', false, NULL),
('randomised controlled trial', 'randomizált kontrollált vizsgálat', 'en', 'hu', 'medical', 'Gold-standard study design in which participants are randomly allocated to treatment or control groups.', false, 'Abbrev: RCT'),
('placebo-controlled', 'placebokontrollos', 'en', 'hu', 'medical', 'Trial design in which one group receives a placebo for comparison.', false, NULL),
('double-blind', 'kettős vak', 'en', 'hu', 'medical', 'Trial design in which neither participants nor investigators know which treatment is administered.', false, NULL),
('evidence-based medicine', 'bizonyítékalapú orvoslás', 'en', 'hu', 'medical', 'Clinical decision-making based on the best available research evidence.', false, 'Abbrev: EBM'),
('meta-analysis', 'metaanalízis', 'en', 'hu', 'medical', 'Statistical combination of results from multiple independent studies.', false, NULL),
('systematic review', 'szisztematikus áttekintés', 'en', 'hu', 'medical', 'Comprehensive synthesis of evidence on a defined clinical question.', false, NULL),
('elderly patients', 'idős betegek', 'en', 'hu', 'medical', 'Patients typically aged 65 years or older.', false, NULL),
('paediatric patients', 'gyermekbetegek', 'en', 'hu', 'medical', 'Patients under 18 years of age.', false, NULL),
('standard of care', 'terápiás standard', 'en', 'hu', 'medical', 'Accepted, established medical treatment for a given condition.', false, NULL),
('treatment protocol', 'kezelési protokoll', 'en', 'hu', 'medical', 'Set of standardised procedures for treating a medical condition.', false, NULL),
('long-term therapy', 'hosszú távú kezelés', 'en', 'hu', 'medical', 'Treatment administered over an extended period, typically months to years.', false, NULL),
('monitoring', 'monitorozás', 'en', 'hu', 'medical', 'Regular observation and testing to assess a patient''s condition or treatment response.', false, NULL);
